all:
	g++ *.cpp -o raytracer -std=c++11 -pthread
	# ./raytracer ./../sample_scenes_v3/inputs/simple.xml                  #DONE!!!
	# ./raytracer ./../sample_scenes_v3/inputs/simple_reflectance.xml      #DONE!!!
	# ./raytracer ./../sample_scenes_v3/inputs/simple_shading.xml          #Done!!!
	# ./raytracer ./../sample_scenes_v3/inputs/cornellbox.xml              #DONE!!!
	# ./raytracer ./../sample_scenes_v3/inputs/mirror_spheres.xml          #DONE!!!
	# ./raytracer ./../sample_scenes_v3/inputs/bunny.xml                   #DONE!!!
	# ./raytracer ./../sample_scenes_v3/inputs/monkey.xml                  #DONE!!!
	# ./raytracer ./../sample_scenes_v3/inputs/berserker.xml               #DONE!!!
	# ./raytracer ./../sample_scenes_v3/inputs/car.xml
	# ./raytracer ./../sample_scenes_v3/inputs/dragon_lowres.xml
	# ./raytracer ./../sample_scenes_v3/inputs/horse_and_mug.xml
	# ./raytracer ./../sample_scenes_v3/inputs/killeroo.xml
	# ./raytracer ./../sample_scenes_v3/inputs/low_poly.xml
