COMMAND_ROLL = 0
COMMAND_BUY = 1
COMMAND_UPGRADE = 2
COMMAND_DOWNGRADE = 3
COMMAND_PICK = 4
COMMAND_BAIL = 5
COMMAND_TELEPORT = 6
COMMAND_PASS = 7

COMMAND_CHOICES = [
    (COMMAND_ROLL, "Roll"),
    (COMMAND_BUY, "Buy"),
    (COMMAND_UPGRADE, "Upgrade"),
    (COMMAND_DOWNGRADE, "Downgrade"),
    (COMMAND_PICK, "Pick"),
    (COMMAND_BAIL, "Bail"),
    (COMMAND_TELEPORT, "Teleport"),
    (COMMAND_PASS, "Pass"),
]


CHANCE_UPGRADE = 0
CHANCE_DOWNGRADE = 1
CHANCE_COLOR_UPGRADE = 2
CHANCE_COLOR_DOWNGRADE = 3
CHANCE_GOTO_JAIL = 4
CHANCE_JAIL_FREE = 5
CHANCE_TELEPORT = 6
CHANCE_LOTTERY = 7
CHANCE_TAX = 8

CHANCE_CHOICES = [
    (CHANCE_UPGRADE, "Upgrade"),
    (CHANCE_DOWNGRADE, "Downgrade"),
    (CHANCE_COLOR_UPGRADE, "Color Upgrade"),
    (CHANCE_COLOR_DOWNGRADE, "Color Downgrade"),
    (CHANCE_GOTO_JAIL, "Goto Jail"),
    (CHANCE_JAIL_FREE, "Jail free"),
    (CHANCE_TELEPORT, "Teleport"),
    (CHANCE_LOTTERY, "Lottery"),
    (CHANCE_TAX, "Tax"),
]


USER_STATUS_NOT_READY = 0
USER_STATUS_READY = 1
USER_STATUS_IN_GAME = 2

USER_STATUS_CHOICES = [
    (USER_STATUS_NOT_READY, "Not Ready"),
    (USER_STATUS_READY, "Ready"),
    (USER_STATUS_IN_GAME, "In Game"),
]

USER_ACTION_STATUS_MUST_ROLL = 0
USER_ACTION_STATUS_CAN_PASS = 1
USER_ACTION_STATUS_MUST_PASS = 2
USER_ACTION_STATUS_MUST_PICK_AND_TELEPORT = 3
USER_ACTION_STATUS_MUST_PICK_AND_UPDOWNGRADE = 4

USER_ACTION_STATUS_CHOICES = [
    (USER_ACTION_STATUS_MUST_ROLL, "Must Roll"),
    (USER_ACTION_STATUS_CAN_PASS, "Can Pass"),
    (USER_ACTION_STATUS_MUST_PASS, "Must Pass"),
    (USER_ACTION_STATUS_MUST_PICK_AND_TELEPORT, "Must Pick & Teleport"),
    (USER_ACTION_STATUS_MUST_PICK_AND_UPDOWNGRADE, "Must Pick & Up/Downgrade"),
]

CELL_TYPE_START = 0
CELL_TYPE_PROPERTY = 1
CELL_TYPE_TAX = 2
CELL_TYPE_JAIL = 3
CELL_TYPE_CHANCE = 4
CELL_TYPE_TELEPORT = 5

CELL_TYPE_CHOICES = [
    (CELL_TYPE_START, "start"),
    (CELL_TYPE_PROPERTY, "property"),
    (CELL_TYPE_TAX, "tax"),
    (CELL_TYPE_JAIL, "jail"),
    (CELL_TYPE_CHANCE, "chance"),
    (CELL_TYPE_TELEPORT, "teleport"),
]
