
all:
	make clean rasterizer

rasterizer:
	g++ -std=c++11 -O3 *.cpp -o rasterizer
clean:
	rm -f rasterizer

# clipping_example
# ./rasterizer ../inputs/clipping_example/empty_box_clipped.xml
# culling_disabled_inputs
# ./rasterizer ../inputs/culling_disabled_inputs/empty_box.xml
# ./rasterizer ../inputs/culling_disabled_inputs/filled_box.xml
# ./rasterizer ../inputs/culling_disabled_inputs/flag_brazil.xml
# ./rasterizer ../inputs/culling_disabled_inputs/flag_czechia.xml
# ./rasterizer ../inputs/culling_disabled_inputs/flag_czechia_alternative.xml
# ./rasterizer ../inputs/culling_disabled_inputs/flag_eu.xml
# ./rasterizer ../inputs/culling_disabled_inputs/flag_eu_alternative.xml
# ./rasterizer ../inputs/culling_disabled_inputs/flag_germany.xml
# ./rasterizer ../inputs/culling_disabled_inputs/flag_turkey.xml
# ./rasterizer ../inputs/culling_disabled_inputs/flag_turkey_alternative.xml
# ./rasterizer ../inputs/culling_disabled_inputs/horse_and_mug.xml
# ./rasterizer ../inputs/culling_disabled_inputs/sample.xml

# culling_disabled_inputs
# ./rasterizer ../inputs/culling_enabled_inputs/empty_box.xml
# ./rasterizer ../inputs/culling_enabled_inputs/filled_box.xml
# ./rasterizer ../inputs/culling_enabled_inputs/flag_brazil.xml
# ./rasterizer ../inputs/culling_enabled_inputs/flag_czechia.xml
# ./rasterizer ../inputs/culling_enabled_inputs/flag_czechia_alternative.xml
# ./rasterizer ../inputs/culling_enabled_inputs/flag_eu.xml
# ./rasterizer ../inputs/culling_enabled_inputs/flag_eu_alternative.xml
# ./rasterizer ../inputs/culling_enabled_inputs/flag_germany.xml
# ./rasterizer ../inputs/culling_enabled_inputs/flag_turkey.xml
# ./rasterizer ../inputs/culling_enabled_inputs/flag_turkey_alternative.xml
# ./rasterizer ../inputs/culling_enabled_inputs/horse_and_mug.xml
# ./rasterizer ../inputs/culling_enabled_inputs/sample.xml

# different_projection_type
# ./rasterizer ../inputs/different_projection_type/flag_turkey/flag_turkey_orthographic.xml
# ./rasterizer ../inputs/different_projection_type/flag_turkey/flag_turkey_perspective.xml
# ./rasterizer ../inputs/different_projection_type/horse_and_mug/horse_and_mug_orthographic.xml
# ./rasterizer ../inputs/different_projection_type/horse_and_mug/horse_and_mug_perspective.xml

